### ISSUE TITLE
Please catch and convert platform-specific exceptions.

### ISSUE THREAD

**Issue by Alxandr** [paulcbetts/ModernHttpClient#115]
Currently, I can't really catch the exceptions I get in a PCL, cause they have types in the `Java.` namespace (and similar). These should be caught by `ModernHttpClient` and converted either into standard `System.Net.Http` exceptions, or custom `ModernHttpClient` ones.

Oh, and if I make you a working, and reasonable PR, how fast can you have a new version out on NuGet? I'd really like this feature without having to add the source to my project (and retain the ability to just "update" later).

**Comment by Yortw** [comment]
I appreciate this is a breaking change, but I think the original concern is valid.

Can we not either have a new major version with the breaking change in it, or (horror) a property on the handler that says whether to wrap exceptions or not (defaulting to false to preserve existing behaviour)? At least that way we would have a choice.

**Comment by ianlevesque** [comment]
This definitely bit us recently.  ModernHttpClient works essentially as a drop-in replacement, except that now all the exception handling code I had based on HttpRequestException is completely ignored and my application bombs out on Java.Net.Whatever exceptions instead. Since all of our http handling is being done in shared code without access to Java.Net, I guess we will be forced to add many catch Exception wrappers if we continue to use this :frowning:

**Comment by paulcbetts** [comment]
@ianlevesque So, how will your code change if you run a Find Replace HttpRequestException => Exception?

**Comment by ianlevesque** [comment]
@paulcbetts that's not a good option for us because we are using the ASP.NET Web Client libraries (i.e. System.Net.Http.Formatting) which allows us to ReadAsAsync<SomeDataContractClass> and parse JSON automatically while reading the response.  We have had errors in our JSON contracts that would have been caught and squashed by cathing Exception but are not caught by HttpRequestException.

**Comment by ianlevesque** [comment]
We ultimately opted to just discontinue use on Android, iOS does not throw any platform-specific exceptions and works well.  I can understand both perspectives here, but for us we were able to just tweak our HTTPS configuration to no longer require ModernHttpClient for Android.

**Comment by paulcbetts** [comment]
Gonna close this, thanks for the input everyone!
