### ISSUE TITLE
Make request cache policy configurable (iOS)

### ISSUE THREAD

**Issue by rintje** [paulcbetts/ModernHttpClient#137]
Hi,

I noticed the request cache policy is hardcoded to NSUrlRequestCachePolicy.UseProtocolCachePolicy in NativeMessageHandler on iOS, meaning NSURLRequest should obey cache control headers when specified. 
However, this does not seem to work 100% ok for conditional requests (in my experience).

Would it be a good idea to make it possible to choose for the other policies available? Especially ReloadIgnoringLocalCacheData is a good one, which disables caching entirely. I know i can disable the cache by setting shared NSUrlCache memory to 0, but this is probably a cleaner solution.

Some more info about NSUrl cache policies:
http://nshipster.com/nsurlcache/

**Comment by Tableau-David-Potter** [comment]
I also need this behavior - to disable OS-based caching completely so our app can manage it.  The easiest way to implement this looks like to add a property to the NativeMessageHandler class like this:

    public RequestCachePolicy CachePolicy { get; set; }

In the constructor, set this property to have a default value:

    this.CachePolicy = NSUrlRequestCachePolicy.UseProtocolCachePolicy;

Then in the `SendAsnc()` method use the value from the property instead of hard-coding it:

    CachePolicy = this.CachePolicy,

I'll probably implement this and submit a pull request once we've tested it.

**Comment by Tableau-David-Potter** [comment]
After further review, we've decided to go a much simpler direction since there isn't a one-to-one mapping between Apple and Microsoft cache policies.  Now what we've done is add an EnableCaching property on NativeMessageHandler and then it just supplies the correct Apple policy based on the property.  I've submitted a pull request to Paul with this change which I hope he'll accept soon.

**Comment by paulcbetts** [comment]
Fixed in #145
