### ISSUE TITLE
MIT License Header

### ISSUE THREAD

**Issue by lhaussknecht** [paulcbetts/ModernHttpClient#219]
As far as I recognize, the license for ModernHttpClient is the MIT License. 

Would you mind adding the header 
 
> The MIT License (MIT)

as statet here (https://opensource.org/licenses/MIT) on top of the COPYING file (https://github.com/paulcbetts/ModernHttpClient/blob/master/COPYING)?

One of my clients fear using OSS with the wrong license. Thanks!

**Comment by nberardi** [comment]
That is really uncommon for the MIT License. 
https://en.m.wikipedia.org/wiki/MIT_License

This fearful client is going to always have you jump through hoop with the BSD or MIT license if this is a requirement of theirs. It might be better to educate them on the license instead of asking projects to change their licenses.

**Comment by lhaussknecht** [comment]
You are absolutly right! 

The client wanted me to categorize all packages we are using by license type. Some of them use the header some not.

Please close the issue. Thanks!
